name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: xeus-nelson-kernel
          environment-file: environment.yml

      - name: Dev install
        run: |
          set -eux
          jlpm
          jlpm run lint:check
          jlpm run build
          python -m pip install -v .

          jupyter labextension list 2>&1 | grep -ie "@jupyterlite/xeus-nelson-kernel.*OK"

      - name: Build the extension
        run: |
          pip install build
          python -m build --sdist
          cp dist/*.tar.gz jupyterlite-xeus-nelson.tar.gz
          pip uninstall -y jupyterlite-xeus-nelson jupyterlab
          rm -rf jupyterlite-xeus-nelson

      - uses: actions/upload-artifact@v2
        with:
          name: jupyterlite-xeus-nelson-sdist
          path: jupyterlite-xeus-nelson.tar.gz

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: actions/download-artifact@v2
        with:
          name: jupyterlite-xeus-nelson-sdist
      - name: Install and Test
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)
          pip install jupyterlite-xeus-nelson.tar.gz
          pip install jupyterlab
          jupyter labextension list 2>&1 | grep -ie "@jupyterlite/xeus-nelson-kernel.*OK"

          # TODO: add JupyterLite browser check
          # python -m jupyterlab.browser_check --no-chrome-test
